name: publish gh-pages docs
on:
  push:
    branches:
      - master
jobs:

  publish:
    name: publish docs
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]
    steps:
    - name: checkout
      uses: actions/checkout@v1
      with:
        submodules: true
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install and configure Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true # Keeps virtualenv inside project directory
    - name: Install dependencies
      run: poetry install --no-interaction
    - run: bash docs/build_external.sh
    - run: poetry run properdocs build
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
